//  Copyright 2016 The Sawdust Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

/**
 * <pre>
 * Java provides Statement, PreparedStatement and CallableStatement for executing queries.
 *  Statement is used for general purpose queries,
 *  PreparedStatement is used for executing parametric query
 *  CallableStatement is used for executing Stored Procedures.
 *
 * PreparedStatement in Java is one of several ways to execute SQL queries using JDBC API.
 * PreparedStatement
 *     -- prevents SQL Injection attacks
 *     -- good performance.
 *
 * get PreparedStatement object by calling
 *      connection.prepareStatement()
 *
 *  SQL queries passed to this method goes to Database for pre-compilation if JDBC driver supports it.
 *  If it doesn't then pre-compilation occurs when you execute prepared queries.
 *
 *  Prepared Statement queries are pre-compiled on database and there access plan will be reused to execute
 *  further queries which allows them to execute much quicker than normal queries generated by Statement object.
 *
 */
package JDBC;