include_defs(
  '//lib/cook_prebuilt_jar.py'
)

cook_prebuilt_jar(
  name = 'guava',
  group_id = 'com.google.guava',
  artifact_id = 'guava',
  version = '18.0',
  bin_sha1 = 'cce0823396aa693798f8882e64213b1772032b09',
  src_sha1 = 'ad97fe8faaf01a3d3faacecd58e8fa6e78a973ca'
)

cook_prebuilt_jar(
  name = 'junit',
  group_id = 'junit',
  artifact_id = 'junit',
  version = '4.12',
  bin_sha1 = '2973d150c0dc1fefe998f834810d68f278ea58ec',
  src_sha1 = 'a6c32b40bf3d76eca54e3c601e5d1470c86fcdfa',
  deps = [
    ':hamcrest-core'
  ],
)

cook_prebuilt_jar(
  name = 'hamcrest-core',
  group_id = 'org.hamcrest',
  artifact_id = 'hamcrest-core',
  version = '1.3',
  bin_sha1 = '42a25dc3219429f0e5d060061f71acb49bf010a0',
  src_sha1 = '1dc37250fbc78e23a65a67fbbaf71d2e9cbc3c0b',
  visibility = [
    '//:junit'
  ]
)

cook_prebuilt_jar(
  name = 'truth',
  group_id = 'com.google.truth',
  artifact_id = 'truth',
  version = '0.27',
  bin_sha1 = 'bd17774d2dc0fffa884d42c07d2537e86c67acd6',
  src_sha1 = '68a2f3f4ec1d0f3e63d0fa32dc9a13d6f612c80b',
  deps = [
    ':guava',
    ':junit'
  ],
  visibility = [
    '//dataStructuresAndAlgorithms:data_structures_and_algorithms_test'
  ]
)

cook_prebuilt_jar(
  name = 'slf4j-simple',
  group_id = 'org.slf4j',
  artifact_id = 'slf4j-simple',
  version = '1.7.13',
  bin_sha1 = '8f0d8b5bf0ff295162360a0a5ebb9c945bd2b685',
  src_sha1 = '94068657ccce29fd6c93ed770c394213fcc9b41a',
  deps = [
    ':slf4j-api'
  ]
)

cook_prebuilt_jar(
  name = 'slf4j-api',
  group_id = 'org.slf4j',
  artifact_id = 'slf4j-api',
  version = '1.7.13',
  bin_sha1 = '7fcf30c25b8f4a9379b9dad0d3f487b25272c026',
  src_sha1 = '96e785df399a4e1a6c030877097807b7e18520cc'
)
