
.[big red]#Bruce Zu's Resume#
****
****

:Gerrit: https://www.gerritcodereview.com/about.md
:Linkedin: https://www.linkedin.com/in/bruce-zu-98b82018
:Facebook: https://www.facebook.com/bruce.zu
:Github: https://github.com/BruceZu
:mycommits: https://gerrit-review.googlesource.com/#/q/author:%22Bruce+Zu%22
:whatisjenkins: https://jenkins.io/
:whatisgerrit: https://www.gerritcodereview.com/index.md
:My Create project: https://gerrit-review.googlesource.com/#/q/topic:create-project-ui

- Like algorithm, math, coding to defeat every kind technology issue and challenge.
I appreciate *hacker culture*, *concise* and *quick* code which is improving the life of human kind.
Excited to work in *open source* community and interested in distributed application systems.
Having passion of continuous improvement through refactoring and introducing new technologies.
- Have been touching *Java*/*Java EE* since 2002. *Full stack* or *back end*. +
- Contributed to *open source* {Gerrit}[Google Gerrit Code Review] since 2011. +
- Administrator experience (*8 years*) of web applications running on *Linux*.



[small Gray]#Londonderry Dr, Santa Clara, CA 95050 |
(626) 747-6721 | English, Mandarin | zu.bruce.china@gmail.com +
{Linkedin}[Linkedin] {Facebook}[Facebook] {Github}[Github]#

'''
[small Gray]#_Apr 2015 -  Apr 2016_# +
[small Gray]#Relocated to CA from Beijing# +
[small Gray]#Following Gerrit community# |
[small Gray]#Acquiring Data Structures and Algorithms# +
[small Gray]#Got *EAD* and *SSN* in April, 2016# |
[small Gray]#Looking for a job now in CA or Seattle | _I can work immediately_# +

'''
=== *EMPLOYMENT*

==== Sony Mobile — Senior Software Engineer, full stack, mainly focus on back end

[small Gray]#_Sep 2011 -  Apr 2015_# +
[small Gray]#Sony Mobile {whatisgerrit}[Gerrit] team is a global team (4 ~ 8 members from Sweden, Tokyo, Brazil and Beijing) supporting 7000+ inner end users.#

* Tackled daily *Gerrit/Git/Repo* related issues and feature requirements for CM users, Git Admin and developers. +
* Contributed *140+ {mycommits}[commits]* to improve and strengthen Gerrit functions to make users convenient. +
* Received *2 awards* for outstanding contributions for software development. +

[small Gray]#_Nov 2010 - Sep 2011_# +
[small Gray]#Sony Mobile {whatisjenkins}[Jenkins] team is a global team (4 ~ 8 members) including Beijing, Lund and Tokyo sites.#

* Tackled daily *Jenkins* related issues for developers and CM users. +
* Developed *Gerrit-trigger-plugin*. +
* Maintained *Jenkins* servers. +

==== Canon — DBA & Senior Software Engineer, back end

[small Gray]#_Apr 2007 - Mar 2010_# +
[small Gray]#E-Order, E-Bank, E-Parts ... web applications#

* Perform *query optimization*, tuning of complex queries, write efficient SQL and Stored Procedures. +
* Tackled backup & restore issues of *DB2* databases, *MS SQL server* databases. +
* *Developed* and maintained a *real-time* application to exchange data between web applications and core application. +

==== CS&S — Software Engineer, full stack, mainly focus on back end

[small Gray]#_Mar 2003 - Feb 2007_# +
[small Gray]#Large scale distributed web applications built for Guangdong Province China using *Java EE, Oracle, BEA Weblogic*.#

* Designed and developed payment module of _Centralized Taxes Payment Application_.  +
* Designed _Social Insurance Payment Application_. +
* Received *several awards* for outstanding performance in team.

==== Cernet — Intern, full stack, mainly focus on back end

[small Gray]#_Mar 2002 - Dec 2002_# +
[small Gray]#E-payment Application#

* Developed all features of admin module from front-end to back-end using *Java EE, Oracle, JBoss*.

'''
=== *EDUCATION*

[small Gray]#_Sep 2000 - Mar 2003_# +
[Gray]#University of Science and Technology Beijing - Master# +
[small Gray]#_Sep 1994 - Mar 1998_# +
[Gray]#University of Science and Technology Hebei - Bachelor# +

'''
=== *SKILLS* [small Gray]#_( years)#_

Open Source Software Development
Gerrit/Git [small Gray]#_(5)_#, Jenkins [small Gray]#_(5)_#, BUCK [small Gray]#_(3)_#, Maven [small Gray]#_(2)_# +
Java/Java EE [small Gray]#_(14)_#, Python [small Gray]#_(2)_# +
C/C++ [small Gray]#_(2)_#, Javascript/HTML/CSS [small Gray]#_(2)_# +
Linux [small Gray]#_(7)_#, Bash +
Google Guice [small Gray]#_(5)_#, Google Guaua [small Gray]#_(5)_#, Google GWT [small Gray]#_(5)_# +
RESTful API, develop client & server side +
Tomcat [small Gray]#_(3)_#, Jetty, Bea Weblogic [small Gray]#_(3)_#, IBM WebShpere [small Gray]#_(2)_# +
SQL DB: Oracle [small Gray]#_(5)_#, Postgres [small Gray]#_(4)_#, IBM DB2 [small Gray]#_(3)_#, SQL Server [small Gray]#_(3)_# +
IBM MQ [small Gray]#_(2)_#, Apache Lucene +
Scrum/Agile/Sprint [small Gray]#_(3)_# +



'''
=== *Ability*

* An independent quick learner especially on Java technologies. +
[small Gray]#When I worked in SonyMobile, I was assigned to develop Gerrit and Jenkins plugin which I had never heard of at the very beginning.
  However, I could shift output quickly without any help since I am good at Java.# +
* Positive team spirit and interpersonal skills. +
* Excellent attention to detail, troubleshooting and analytical skills. +

'''



[NOTE]
====
[small Gray]#If you want more information, please refer the following Deployment Detail information#
====


.[big red]#EMPLOYMENT DETAIL#
****
****

==== Sony Mobile

[small Green]#_Sep 2011 -  Apr 2015_# +

.Job Title

Senior Software Engineer, full stack, mainly focus on back end.

.Job Function
I was a member of global Gerrit development team, supporting Git Admin team, CM team and developers
by delivering new features and bugfixes. Members are from Sweden, Tokyo, Brazil and Beijing.
We also keep close relation with other Gerrit community core contributors who works for Google,
SAP, Qualcomm and OpenStack.

.Application introduction
:gerrit-case: https://gerrit.googlesource.com/homepage/+/md-pages/docs/ShowCases.md

Gerrit Code Review::

Gerrit provides access via browser, *RESTful API* and *SSH Command line*. Gerrit select *GWT* as its web framework,
uses *CodeMirror* to show the `git diff` result on web. A new UI is under building using *Polymer*.
Gerrit replaced nearly all *GWT RPC* implementation with its own *RESTful API*.
The *SSH Command line* features are built with *Apache MINA*'s sub project *Apache SSHD*.
Gerrit notification functions including *Hook*, *Stream-event* and *E-mail*.
Gerrit stores data in *Git* repositories and *SQL database*.
Gerrit does not use *Hibernate*. Instead, it supports 9 kinds of *SQL database* with its own *open source* tiny *ORM* library,
which is built by using *ObjectWeb ASM 3, H2* and *ANTLR 3*, e.g. *Oracle, MySQL, H2, PostgreSQL, DB2*. However,
Gerrit is moving the data stored in DB into `git notes`. This is a step towards implementing open-source version of *multi-master* feature.
Gerrit caches search results in memory, disk of server side and client side via browser.
Gerrit builds second index using *Lucene* and *Protocol Buffers*.
Gerrit provides search function, and the grammar is built by using *Antlr 3*.
Gerrit has replication function, which now is a plugin, to enable *master-slave* mode.
Gerrit uses *Google Guice*, not *Spring*, as dependency injection framework.
Gerrit supports developing *Gerrit plugin*. Gerrit uses *BUCK* to build source code, run *Junit* test, wrap release file (war).
BUCK runs faster that *Maven*. Gerrit provides init command to do every initial works and startup Gerrit automatically.
Gerrit has tons framework.


The Sony Mobile Gerrit server::

Gerrit server runs in *Tomcat* web container behind an *Apache* web server.
Gerrit server is *master-slave* mode, one master server and on average *7 slave servers* * *3 sites* accessed by *7000+* end users in total.
Sony Mobile Gerrit server uses *PostgreSQL* that has replication features. Each Gerrit slave server has a *PostgreSQL* database.
On each site, the Gerrit slave servers are located behind balance servers that balance the requests from local developers and local *Jenkins* servers.



.Achievements

Develop :::
Some features, e.g.:

- [*] Create project (*SSH command* and *RESTful API*) +
- [*] Add file comment to a patch +
- [*] Enable branch specified label +
- [*] Add reviewers in batch by *LDAP* group +
- [*] Add new system configuration options +
- [*] Enable register email registered automatically +


:My-contribution: https://gerrit-review.googlesource.com/#/q/author:bruce.zu
:::
Details: {My-contribution}[ my commits] contributed to Gerrit community.

Daily support :::

- [*] Tackled issues related to Gerrit, Apache, Tomcat with CM user and Git Admin  +
- [*] Tried new Gerrit version and Gerrit plugins in Test Environment +

[small Green]#_No 2010 ~ Sep 2011_# +

.Job Function

Jenkins master.

.Job Title

Staff Engineer

.Application introduction

Sony mobile has few *Jenkins servers* in each site with hundreds of slave machines for developers, CM teams.

.Achievements

Admin Jenkins Server

- [*]  Evaluated/Upgraded Jenkins new version and Jenkins plugins +
- [*]  Setup and configured new Jenkins slaves. Allocated slave groups to Jenkins jobs, Tuned slave groups +
- [*]  Monitored Jenkins server/jobs/slaves and tackled issues +

Develop

- [*] Took part in developing Jenkins plugin: *Gerrit-trigger-plugin* +

==== Canon China

[small Green]#_Apr 2007 - Mar 2010_# +

.Job Title

Senior Software Engineer, back end.

.Job Function

Supervise all local web applications

.Application introduction

Cannon China local applications ::
Web applications, e.g. e-order, e-bank, e-parts ... They are built using *Java/Java EE, DB2* or *MS SQL Server*.
Their databases need exchange data with core application that is built using *AS400* and *DB2*.

.Achievements

DBA

- [*] Perform query optimization and tuning of complex queries, write efficient SQL and Stored Procedures.
 That access several million rows across several database tables. Tuned SQL statement of web applications,
  e.g. reduced the running time of some SQL statements to be less than *5 seconds* from *2+ minutes*. +
- [*] Setup MS SQL Server database backup plan and carried it out. +
- [*] Tacked day-to-day issues of DB2 backup to tape and wrote tutorial. +

Develop using the API of *IBM MQ* and *Java RMI*:

- [*] Designed, developed, tested, deployed and maintained a real-time application used to sync data between web applications and core applications. +

==== China Software & Service

[small Green]#_Mar 2003 - Feb 2007_# +

.Job Title
Software Engineer, full stack, mainly focus on back end +

.Job Function
With other members developed 2 web applications for Guangdong Province China .

- Centralized Taxes Payment Application.
- Social Insurance Payment Application.

.Application introduction

Centralized Taxes Payment Application ::

The application provides local tax services for the whole province. It is a *large-scale distributed Java EE based web application* built
with *Oracle RAC* and *Weblogic cluster*. The number of GDP and people of Guandong Province is greater than that of Taiwan.
The number of this application’s *online users (2000+)* and concurrent users is very tremendous. It is also a *big data* application.
It is *multi-tier, browser/server mode* and *client/server mode* architecture.
Users can access it via telephone, browser and client side application.
It also communicates with other applications of banks and other government departments.


.Achievements

- [*] Design and coding features like online payment and printing cash receipt, General-purpose Tax Payment Certificate. +

.Application introduction

Social Insurance Payment Application ::
This application is used to collect 5 kinds of social insurance fee from employer for their employee.
It force the employer to pay these social insurance together with the local taxes +

I was in charge of system requirement and system design. +

.Achievements

- Design:

- [*] Wrote out system requirement with end user. Made clear the *boundary of system*, wrote out *user cases*. +
- [*] Combed out the business data flow, draw out *business data module*.  +
- [*] Created *physical data module*, DB scheme. +
- [*] Divided system into sub modules. +

- ETL:

- [*] Took part in *ETL* work between old application DB and new application DB. +


==== Cernet — Intern
[small Green]#_Mar 2002 - Dec 2002_# +

.Job Title

Software Engineer, full stack, mainly focus on back end .

.Job Function

Took part in developing E_Payment web application

.Application introduction

E_Payment application::
It is online payment application like Paypal to provide payment service used by Cernet web site.
Its framework mocked the Sun pet store using *JavaScript, JSP, Servlet, JDBC, EJB* +

.Achievements
Developed admin module of E-payment application from the *front-end* to *back-end*
Features includes

- [*] Register/update new user information. +
- [*] Manage user authority via user's group. +

Developed common library

- [*] Defined *DTD*, a Document Type Definition, and developed a parser to parse a given *XML* according the DTD. +


