python_binary(
  name = 'download_file',
  main = 'download_file.py',
  deps = [
    ':util'
  ],
  visibility = [
    'PUBLIC'
  ]
)

python_library(
  name = 'util',
  srcs = [
    'util.py',
    '__init__.py'
  ]
)