/**
 * <pre>
 * Java provides Statement, PreparedStatement and CallableStatement for executing queries.
 *  Statement is used for general purpose queries,
 *  PreparedStatement is used for executing parametric query
 *  CallableStatement is used for executing Stored Procedures.
 *
 * PreparedStatement in Java is one of several ways to execute SQL queries using JDBC API.
 * PreparedStatement
 *     -- prevents SQL Injection attacks
 *     -- good performance.
 *
 * get PreparedStatement object by calling
 *      connection.prepareStatement()
 *
 *  SQL queries passed to this method goes to Database for pre-compilation if JDBC driver supports it.
 *  If it doesn't then pre-compilation occurs when you execute prepared queries.
 *
 *  Prepared Statement queries are pre-compiled on database and there access plan will be reused to execute
 *  further queries which allows them to execute much quicker than normal queries generated by Statement object.
 *
 */
package JDBC;